name: "Build Documentation"
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          conda-channels: conda-forge
          python-version: 3.8
      - name: Install Env
        shell: bash
        run: |
          python --version
          conda env create -f environment.yml
      - name: Install Our Package
        shell: bash
        run: |
          source activate agu-ossi-2020
          pip install -e .
      - name: Build Documentation
        shell: bash
        run: |
          source activate agu-ossi-2020
          cd docs/
          make html
      - uses: actions/upload-artifact@v2
        with:
          name: html
          path: docs/build/html/
  deploy:
    runs-on: ubuntu-latest
    needs: docs
    # Only deploy from master
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # NOTE: this repo usese `main` not `master`
    # Only deploy from tags
    # if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v1
      - name: Download Documentation
        uses: actions/download-artifact@v2
        with:
          name: html
          path: docs/build/html
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/build/html # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
