name: Testing

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  setup-build:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: [3.8, 3.9, "3.10", "3.11"] 

    steps:
    - uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        activate-environment: aurora-test
        python-version: ${{ matrix.python-version }}

    - name: Install Env
      run: |
        python --version
        conda install -c conda-forge pytest pytest-cov certifi">=2017.4.17" pandoc
        pip install -r requirements-dev.txt
        pip install git+https://github.com/kujaku11/mt_metadata.git@fcs
        pip install git+https://github.com/kujaku11/mth5.git@fc

    - name: Install Our Package
      run: |
        pip install -e .
        conda list

    - name: Run Tests
      run: |
        # pytest -s -v tests/synthetic/*.py --cov=./ --cov-report=xml --cov=aurora
        pytest -s -v --cov=./ --cov-report=xml --cov=aurora

    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true

    - name: Build Doc
      if: ${{ (github.ref == 'refs/heads/main') && (matrix.python-version == '3.8')}}
      run: |
        cd docs
        make html
        cd ..

    - name: GitHub Pages
      if: ${{ (github.ref == 'refs/heads/main') && (matrix.python-version == '3.8')}}
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with:
        build_dir: docs/_build/html
        # Write the given domain name to the CNAME file
        # fqdn: aurora.simpeg.xyz
        # Allow Jekyll to build your site
        jekyll: false # optional, default is true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
